global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'rules.yaml'

scrape_configs:
  - job_name: 'manager'
    static_configs:
    - targets: ['[사설ip]:9100']
      labels:
        service : 'manager'

  - job_name: 'manager_container'
    static_configs:
    - targets: ['[사설ip]:8081']
      labels:
        service : 'manager_container'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - [사설ip]:9093
