services:
  grafana:
    image: grafana/grafana
    container_name: my_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=test123
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - my_project
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: my_prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    restart: always
    networks:
      - my_project
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: my_cadvisor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro #ro : readonly
      - /dev/disk:/dev/disk:ro
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - my_project
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    container_name: my_alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yaml
    restart: always
    networks:
      - my_project

  node_exporter:
    image: prom/node-exporter
    container_name: my_exporter
    ports:
      - target: 9100
        published: 9100
        protocol: tcp
        mode: host
    deploy:
      mode: global
    networks:
      - my_project

  proxy:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/snippets:/etc/nginx/snippets
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./proxy/html:/var/www/html
    container_name: my_proxy #(단, 서비스로 사용 시[도커 스웜] 무시되어집니다. 필요없어집니다) 단일로 구성했을 경우 필요합니다.
    depends_on:
      - nginx
      - wordpress
    networks:
      - my_project

  php:
    image: php:7.4-fpm
    container_name: my_php
    volumes:
      - ./nginx/html:/var/www/html
    command:
      - /bin/sh
      - -c
      - |
        echo "security.limit_extensions = .php .phtml .php3 .php4 .php5 .html .htm" >> /usr/local/etc/php-fpm.d/www.conf
        php-fpm
    networks:
      - my_project

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/var/www/html
    container_name: my_nginx
    depends_on:
      - php
    networks:
      - my_project
    
  db:
    image: mysql:latest
    volumes:
    - ./db/conf.d:/etc/mysql/conf.d
    env_file: ./db/.env
    environment:
      TZ: Asia/Seoul
    container_name: my_mysqldb
    networks:
      - my_project

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    environment: #이상한 것은 .env_file이 작동되지 않습니다.
      TZ: Asia/Seoul
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress/html:/var/www/html
    container_name: my_wordpress
    networks:
      - my_project

  certbot:
    image: certbot/certbot
    container_name: my_certbot
    depends_on:
      - proxy
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./proxy/html:/var/www/html
      - ./certbot/log:/var/log/letsencrypt
    command: certonly --dry-run --agree-tos --no-eff-email --email myemail@gmail.com --webroot --webroot-path=/var/www/html --force-renewal -d [도메인].com -d www.도메인.com
    networks:
      - my_project
 
  flask:
    build: ./flask
    image: project/flask
    restart: always
    volumes:
      - ./flask/log:/usr/src/program/log
    container_name: my_flask
    command: gunicorn -w 1 -b 0.0.0.0:80 wsgi:server
    networks:
      - my_project

networks:
  my_project:
    driver: bridge
