services:
  mydb:
    image: db_test
    env_file: ./db/.env
    deploy:
      mode: global

  wordpress:
    image: word_test
    env_file: ./db/.envw
    ports:
      - 80:80
    deploy:
      mode: global
